<?php

namespace LuckyRomka\Blog;

use Illuminate\Support\ServiceProvider;

class BlogServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        if ($this->app->runningInConsole()) {
            //include __DIR__.'/routes.php';
         //   dd('ass');
        }

        $this->loadRoutesFrom(__DIR__.'/routes.php');
        $this->loadViewsFrom(__DIR__.'/Views', 'LaravelBlog');
        $this->publishes([
            __DIR__.'/../config/laravelblog.php'        => config_path('LaravelBlog.php'),
        ]);
    }
     public function register()
     {
         //parent::register(); // TODO: Change the autogenerated stub
     }
}
