<?php

namespace LuckyRomka\Blog;

use Illuminate\Support\ServiceProvider;

class BlogServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
       // dd('ass');
        if ($this->app->runningInConsole()) {
            include __DIR__.'/routes.php';
         //   dd('ass');
        }

        $this->publishes([
            __DIR__.'/Config/LaravelBlog.php'        => config_path('LaravelBlog.php'),
        ]);
    }
     public function register()
     {
         //parent::register(); // TODO: Change the autogenerated stub
     }
}
